
## default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: salt-dev
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
#okta:
#  oauth2:
#    issuer: https://dev-98888155.okta.com/oauth2/default
#    client-id: 0oa8tbhsa7ecapYI65d7
#    client-secret: pNijfBuFXsPKybqBaMrDc4ZL88sIoXihbMvTk89K

#    scope: openid,courses,email,profile
#    groupsClaim: grp