## DB config goes here
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: postgresql
  datasource:
#    url: jdbc:postgresql://mouse.db.elephantsql.com/hzjiemrt
#    username: hzjiemrt
#    password: sffIht84O7WVCZRB4rfaOM9J6mIdZWCn
    url: jdbc:postgresql://localhost:5432/rri
    username: postgres
    password: pgpwd
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

## Logging settings
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR