
#### default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/postgres?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}
#    url: jdbc:postgresql://localhost:5432/Plants
#    username: postgres
#    password: pgpwd
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  logging:
    level:
      org:
        springframework:
          boot:
            autoconfigure: ERROR
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: https://dev-leddoa8c1xzu7p1w.us.auth0.com/
auth0:
  audience: http://grdnr.com


          #            client-id: QnI29kMHbukPpYnxyTSCNB1Pzczax3Ct
          #            client-secret: 1L73RmrKpQ323gPUN67SyoWGVAwsgvrWqdS60VeqUeN5ObFX86rPnXYtlaXz6XaC
