
#### default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: salt-dev
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  logging:
    level:
      org:
        springframework:
          boot:
            autoconfigure: ERROR

#  security:
#    oauth2:
#      client:
#        registration:
#          auth0:
#            client-id: QnI29kMHbukPpYnxyTSCNB1Pzczax3Ct
#            client-secret: 1L73RmrKpQ323gPUN67SyoWGVAwsgvrWqdS60VeqUeN5ObFX86rPnXYtlaXz6XaC
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            # trailing slash is important!
#            issuer-uri: https://dev-b1zvhq6qtydtr80k.us.auth0.com/

#  logging.level.org.hibernate.SQL=DEBUG
#  datasource:
#    url: jdbc:postgresql://${POSTGRES_URL}:5432/postgres?sslmode=require
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PWD}
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect:org.hibernate.dialect.PostgreSQLDialect