
#### default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/postgres?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PWD}

#  datasource:
#    url: jdbc:postgresql://localhost/Plants
#    username: postgres
#    password: postgres
#    username: postgres
#    password: pgpwd
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  logging:
    level:
      org:
        springframework:
          boot:
            autoconfigure: ERROR
