
#### default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #    url: jdbc:postgresql://localhost:5432/Plants
    #    username: postgres
    #    password:
    #url: ${ELEPHANT_URL}
    #username: ${ELEPHANT_USER}
  #password: ${ELEPHANT_PWD}
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:Plant;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  logging:
    level:
      org:
        springframework:
          boot:
            autoconfigure: ERROR



#  security:
#    oauth2:
#      client:
#        registration:
#          auth0:
#            client-id: QnI29kMHbukPpYnxyTSCNB1Pzczax3Ct
#            client-secret: 1L73RmrKpQ323gPUN67SyoWGVAwsgvrWqdS60VeqUeN5ObFX86rPnXYtlaXz6XaC
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            # trailing slash is important!
#            issuer-uri: https://dev-b1zvhq6qtydtr80k.us.auth0.com/

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect:org.hibernate.dialect.PostgreSQLDialect